variables:
    TUTOR_PLUGIN: EMI
    TUTOR_EXTRA_ENABLED_PLUGINS: mfe
    TUTOR_PYPI_PACKAGE: EMI
    TUTOR_IMAGES: openedx mfe
    GITHUB_REPO: mexicox/tutor-indigo

stages:
  - build
  - deploy
deploy_prod:
  stage: deploy
  script:
    - source /opt/mexicox/venv/bin/activate
    - rm -rf  "$(tutor config printroot)/env/build/openedx/themes/EMI/*"
    - cp -rf * "$(tutor config printroot)/env/build/openedx/themes/EMI"
    - cd "$(tutor config printroot)/env/build/openedx/themes"
    - pip install -e ./EMI
    - tutor plugins enable EMI
  tags:
    - edx
  only:
    refs:
      - master

deploy_dev:
  stage: deploy
  script:
    - source /opt/mexicox/venv/bin/activate
    - rm -rf  "$(tutor config printroot)/env/build/openedx/themes/EMI/*"
    - cp -rf * "$(tutor config printroot)/env/build/openedx/themes/EMI"
    - cd "$(tutor config printroot)/env/build/openedx/themes"
    - pip install -e ./EMI
    - tutor plugins enable EMI
    - tutor config save
    - tutor local do settheme EMI
    - tutor images build --build-arg EDX_PLATFORM_REPOSITORY=https://github.com/XxjhonWalkerxX/edx-platform.git --build-arg EDX_PLATFORM_VERSION=diegod  openedx
    - tutor local stop 
    - tutor local start -d
  tags:
    - develop
  only:
    refs:
      - develop  
