deploy_dev:
  stage: deploy
  script:
    - source /opt/emi/venv/bin/activate
    - rm -rf  "$(tutor config printroot)/env/build/openedx/themes/emi/*"
    - cp -rf * "$(tutor config printroot)/env/build/openedx/themes/emi"
    - cd "$(tutor config printroot)/env/build/openedx/themes"
    - pip install -e ./emi
    - tutor plugins enable emi
    - tutor config save
    - tutor local do settheme emi
    - tutor images build openedx
    - tutor local stop 
    - tutor local start -d
  tags:
    - develop
  only:
    refs:
      - main  
