[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "emi"
description = "EMI theme plugin for Tutor - Secretaría de Educación Pública"
readme = { file = "README.rst", content-type = "text/x-rst" }
license = { text = "AGPLv3" }
requires-python = ">=3.9"
authors = [{ name = "EMI Team" }, { email = "emi@mexicox.gob.mx" }]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
  "tutor>=20.0.0,<21.0.0", 
  "tutor-mfe>=20.0.0,<21.0.0"
]
dynamic = ["version"]

[project.optional-dependencies]
dev = [
  "tutor[dev]>=20.0.0,<21.0.0"
]

[project.entry-points."tutor.plugin.v1"]
emi = "emi.plugin"

[project.urls]
Code = "https://gitlab.com/mexicox/emi_aprende_mx"
Homepage = "https://gitlab.com/mexicox/emi_aprende_mx"

[tool.setuptools]
packages = ["emi"]

[tool.setuptools.dynamic]
version = {attr = "emi.__about__.__version__"}

[tool.setuptools.package-data]
emi = ["**/*"]